### ISSUE TITLE
debugImplementation "{group}:{name}:{version}" //添加自定义的lint规则包

### ISSUE THREAD

**Issue by designDo** [tianwailaike61/IncrementLint#3]
请教一下这个的原理。是否可以将自定义的lint规则包写在插件中去？

**Comment by tianwailaike61** [comment]
可以的。
class LintPlugin implements Plugin<Project>, DependencyResolutionListener {

    private Project project

    @Override
    void apply(Project project) {
        this.project = project

        project.gradle.addListener(this)
    }

    @Override
    void beforeResolve(ResolvableDependencies resolvableDependencies) {
        def compileDeps = project.getConfigurations().getByName("debugImplementation").getDependencies()
        compileDeps.add(project.getDependencies().create("$GROUP:$NAME:$lintVersion",
                { artifact { name = $NAME; type = TYPE } }))  // 例如 GROUP：com.baidu.test NAME:lint TYPE:aar
        project.gradle.removeListener(this)
    }

    @Override
    void afterResolve(ResolvableDependencies dependencies) {
    }
}

**Comment by designDo** [comment]
感谢 @tianwailaike61
