### ISSUE TITLE
kotlin版本兼容的问题怎么解决的？

### ISSUE THREAD

**Issue by f2rozen541** [tianwailaike61/IncrementLint#5]
报错信息：
Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.resolve.diagnostics.DiagnosticSuppressor$Companion.getEP_NAME()Lcom/intellij/openapi/extensions/ExtensionPointName;

依赖关系：
classpath
+--- com.xx.plugin:frozen:1.0.0
+--- com.xx.lib_client:lib_client:1.0.0
|    \--- com.android.tools.lint:lint-gradle:26.2.1
|         +--- com.android.tools:sdk-common:26.2.1
|         |    +--- com.android.tools:sdklib:26.2.1
|         |    |    +--- com.android.tools.layoutlib:layoutlib-api:26.2.1
|         |    |    |    +--- com.android.tools:common:26.2.1
|         |    |    |    |    +--- com.android.tools:annotations:26.2.1
|         |    |    |    |    +--- com.google.guava:guava:23.0
|         |    |    |    |    |    +--- com.google.code.findbugs:jsr305:1.3.9
|         |    |    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.0.18 -> 2.2.0
|         |    |    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.1
|         |    |    |    |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|         |    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71
|         |    |    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 -> 1.3.40
|         |    |    |    |         |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.40
|         |    |    |    |         |    \--- org.jetbrains:annotations:13.0
|         |    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71
|         |    |    |    |              \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 -> 1.3.40 (*)
|         |    |    |    +--- net.sf.kxml:kxml2:2.3.0
|         |    |    |    +--- com.android.tools:annotations:26.2.1
|         |    |    |    \--- org.jetbrains:annotations:13.0
|         |    |    +--- com.android.tools:dvlib:26.2.1
|         |    |    |    \--- com.android.tools:common:26.2.1 (*)
|         |    |    +--- com.android.tools:repository:26.2.1
|         |    |    |    +--- com.android.tools:common:26.2.1 (*)
|         |    |    |    +--- com.sun.activation:javax.activation:1.2.0
|         |    |    |    +--- org.apache.commons:commons-compress:1.12
|         |    |    |    +--- org.glassfish.jaxb:jaxb-runtime:2.2.11
|         |    |    |    |    +--- org.glassfish.jaxb:jaxb-core:2.2.11
|         |    |    |    |    |    +--- javax.xml.bind:jaxb-api:2.2.12-b140109.1041
|         |    |    |    |    |    +--- org.glassfish.jaxb:txw2:2.2.11
|         |    |    |    |    |    \--- com.sun.istack:istack-commons-runtime:2.21
|         |    |    |    |    +--- org.jvnet.staxex:stax-ex:1.7.7
|         |    |    |    |    \--- com.sun.xml.fastinfoset:FastInfoset:1.2.13
|         |    |    |    +--- com.google.jimfs:jimfs:1.1
|         |    |    |    |    \--- com.google.guava:guava:18.0 -> 23.0 (*)
|         |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    |    +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|         |    |    +--- org.apache.commons:commons-compress:1.12
|         |    |    +--- org.apache.httpcomponents:httpmime:4.5.2
|         |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.3
|         |    |    |         +--- org.apache.httpcomponents:httpcore:4.4.6
|         |    |    |         +--- commons-logging:commons-logging:1.2
|         |    |    |         \--- commons-codec:commons-codec:1.9
|         |    |    \--- org.apache.httpcomponents:httpcore:4.4.5 -> 4.4.6
|         |    +--- com.android.tools.build:builder-test-api:3.2.1
|         |    |    \--- com.android.tools.ddms:ddmlib:26.2.1
|         |    |         +--- com.android.tools:common:26.2.1 (*)
|         |    |         \--- net.sf.kxml:kxml2:2.3.0
|         |    +--- com.android.tools.build:builder-model:3.2.1
|         |    |    \--- com.android.tools:annotations:26.2.1
|         |    +--- com.android.tools.ddms:ddmlib:26.2.1 (*)
|         |    +--- org.bouncycastle:bcpkix-jdk15on:1.56
|         |    |    \--- org.bouncycastle:bcprov-jdk15on:1.56
|         |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
|         |    +--- com.google.protobuf:protobuf-java:3.4.0
|         |    \--- javax.inject:javax.inject:1
|         +--- com.android.tools.external.com-intellij:intellij-core:26.2.1
|         |    \--- org.jetbrains.trove4j:trove4j:20160824
|         +--- com.android.tools.external.org-jetbrains:uast:26.2.1
|         +--- com.android.tools.lint:lint:26.2.1
|         |    +--- com.android.tools.lint:lint-checks:26.2.1
|         |    |    +--- com.android.tools.lint:lint-api:26.2.1
|         |    |    |    +--- com.android.tools:sdk-common:26.2.1 (*)
|         |    |    |    +--- com.google.guava:guava:23.0 (*)
|         |    |    |    +--- com.android.tools.lint:lint-kotlin:26.2.1
|         |    |    |    |    +--- com.android.tools.external.com-intellij:intellij-core:26.2.1 (*)
|         |    |    |    |    +--- com.android.tools.external.com-intellij:kotlin-compiler:26.2.1
|         |    |    |    |    +--- com.android.tools.external.org-jetbrains:uast:26.2.1
|         |    |    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40 (*)
|         |    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    |    |    +--- com.android.tools.external.com-intellij:intellij-core:26.2.1 (*)
|         |    |    |    +--- com.android.tools.external.org-jetbrains:uast:26.2.1
|         |    |    |    +--- org.ow2.asm:asm:6.0
|         |    |    |    +--- org.ow2.asm:asm-tree:6.0
|         |    |    |    |    \--- org.ow2.asm:asm:6.0
|         |    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40 (*)
|         |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    |    +--- com.google.guava:guava:23.0 (*)
|         |    |    +--- com.android.tools.external.com-intellij:intellij-core:26.2.1 (*)
|         |    |    +--- com.android.tools.external.org-jetbrains:uast:26.2.1
|         |    |    \--- org.ow2.asm:asm-analysis:6.0
|         |    |         \--- org.ow2.asm:asm-tree:6.0 (*)
|         |    +--- com.android.tools.lint:lint-kotlin:26.2.1 (*)
|         |    +--- com.google.guava:guava:23.0 (*)
|         |    +--- com.android.tools.external.org-jetbrains:uast:26.2.1
|         |    +--- com.android.tools.external.com-intellij:kotlin-compiler:26.2.1
|         |    +--- com.android.tools.analytics-library:shared:26.2.1
|         |    |    +--- com.android.tools.analytics-library:protos:26.2.1
|         |    |    |    \--- com.google.protobuf:protobuf-java:3.4.0
|         |    |    +--- com.android.tools:annotations:26.2.1
|         |    |    +--- com.android.tools:common:26.2.1 (*)
|         |    |    +--- com.google.guava:guava:23.0 (*)
|         |    |    \--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|         |    +--- com.android.tools.analytics-library:protos:26.2.1 (*)
|         |    +--- com.android.tools.analytics-library:tracker:26.2.1
|         |    |    +--- com.android.tools:annotations:26.2.1
|         |    |    +--- com.android.tools:common:26.2.1 (*)
|         |    |    +--- com.android.tools.analytics-library:protos:26.2.1 (*)
|         |    |    +--- com.android.tools.analytics-library:shared:26.2.1 (*)
|         |    |    +--- com.google.protobuf:protobuf-java:3.4.0
|         |    |    \--- com.google.guava:guava:23.0 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         +--- com.android.tools.lint:lint-gradle-api:26.2.1
|         |    +--- com.android.tools:sdklib:26.2.1 (*)
|         |    +--- com.android.tools.build:builder-model:3.2.1 (*)
|         |    +--- com.android.tools.build:gradle-api:3.2.1
|         |    |    +--- com.android.tools.build:builder-model:3.2.1 (*)
|         |    |    +--- com.android.tools.build:builder-test-api:3.2.1 (*)
|         |    |    +--- com.google.guava:guava:23.0 (*)
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|         |    \--- com.google.guava:guava:23.0 (*)
|         +--- org.codehaus.groovy:groovy-all:2.4.12
|         +--- org.jetbrains.kotlin:kotlin-reflect:1.2.0 -> 1.3.40 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
+--- com.android.tools.build:gradle:3.2.1
|    +--- com.android.tools.build:builder:3.2.1
|    |    +--- com.android.tools.build:builder-model:3.2.1 (*)
|    |    +--- com.android.tools.build:builder-test-api:3.2.1 (*)
|    |    +--- com.android.tools:sdklib:26.2.1 (*)
|    |    +--- com.android.tools:sdk-common:26.2.1 (*)
|    |    +--- com.android.tools:common:26.2.1 (*)
|    |    +--- com.android.tools.build:manifest-merger:26.2.1
|    |    |    +--- com.android.tools:common:26.2.1 (*)
|    |    |    +--- com.android.tools:sdklib:26.2.1 (*)
|    |    |    +--- com.android.tools:sdk-common:26.2.1 (*)
|    |    |    +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|    |    |    \--- net.sf.kxml:kxml2:2.3.0
|    |    +--- com.android.tools.ddms:ddmlib:26.2.1 (*)
|    |    +--- com.android.tools.analytics-library:protos:26.2.1 (*)
|    |    +--- com.android.tools.analytics-library:shared:26.2.1 (*)
|    |    +--- com.android.tools.analytics-library:tracker:26.2.1 (*)
|    |    +--- com.android.tools.build:apksig:3.2.1
|    |    +--- com.android.tools.build:apkzlib:3.2.1
|    |    |    +--- com.google.code.findbugs:jsr305:1.3.9
|    |    |    +--- com.google.guava:guava:23.0 (*)
|    |    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56 (*)
|    |    |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    |    \--- com.android.tools.build:apksig:3.2.1
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|    |    +--- com.squareup:javawriter:2.5.0
|    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56 (*)
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    +--- org.ow2.asm:asm:6.0
|    |    +--- org.ow2.asm:asm-tree:6.0 (*)
|    |    +--- org.ow2.asm:asm-commons:6.0
|    |    |    \--- org.ow2.asm:asm-tree:6.0 (*)
|    |    +--- org.ow2.asm:asm-util:6.0
|    |    |    \--- org.ow2.asm:asm-tree:6.0 (*)
|    |    +--- it.unimi.dsi:fastutil:7.2.0
|    |    +--- net.sf.jopt-simple:jopt-simple:4.9
|    |    \--- com.googlecode.json-simple:json-simple:1.1
|    +--- com.android.tools.analytics-library:shared:26.2.1 (*)
|    +--- com.android.tools.analytics-library:crash:26.2.1
|    |    +--- com.android.tools:annotations:26.2.1
|    |    +--- com.google.guava:guava:23.0 (*)
|    |    +--- org.apache.httpcomponents:httpmime:4.5.2 (*)
|    |    +--- org.apache.httpcomponents:httpcore:4.4.5 -> 4.4.6
|    |    \--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.3 (*)
|    +--- com.android.tools.lint:lint-gradle-api:26.2.1 (*)
|    +--- com.android.tools.build:gradle-api:3.2.1 (*)
|    +--- androidx.databinding:databinding-compiler-common:3.2.1
|    |    +--- androidx.databinding:databinding-common:3.2.1
|    |    +--- com.android.databinding:baseLibrary:3.2.1
|    |    +--- org.antlr:antlr4:4.5.3
|    |    +--- commons-io:commons-io:2.4
|    |    +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
|    |    +--- com.google.guava:guava:23.0 (*)
|    |    +--- com.squareup:javapoet:1.8.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|    |    +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|    |    +--- com.android.tools:annotations:26.2.1
|    |    \--- com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10
|    |         +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.20 -> 1.3.40 (*)
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
|    +--- com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api
|    +--- org.ow2.asm:asm:6.0
|    +--- org.ow2.asm:asm-analysis:6.0 (*)
|    +--- org.ow2.asm:asm-commons:6.0 (*)
|    +--- org.ow2.asm:asm-util:6.0 (*)
|    +--- net.sf.jopt-simple:jopt-simple:4.9
|    +--- net.sf.proguard:proguard-gradle:6.0.3
|    |    \--- net.sf.proguard:proguard-base:6.0.3
|    +--- com.android.tools.build:bundletool:0.5.0
|    |    +--- com.google.auto.value:auto-value:1.5.2
|    |    +--- com.android.tools.build:aapt2-proto:0.3.1
|    |    |    \--- com.google.protobuf:protobuf-java:3.4.0
|    |    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |    +--- com.google.guava:guava:22.0 -> 23.0 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.4.0
|    |    \--- com.google.protobuf:protobuf-java-util:3.4.0
|    |         +--- com.google.protobuf:protobuf-java:3.4.0
|    |         +--- com.google.guava:guava:19.0 -> 23.0 (*)
|    |         \--- com.google.code.gson:gson:2.7 -> 2.8.5
|    +--- com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10 (*)
|    \--- com.android.tools.build.jetifier:jetifier-processor:1.0.0-alpha10
|         +--- org.ow2.asm:asm:6.0
|         +--- org.ow2.asm:asm-util:6.0 (*)
|         +--- org.ow2.asm:asm-commons:6.0 (*)
|         +--- org.jdom:jdom2:2.0.6
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.20 -> 1.3.40 (*)
|         \--- com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10 (*)
\--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.40
     +--- org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.3.40
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     +--- org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.3.40
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     +--- com.google.code.gson:gson:2.8.5
     +--- de.undercouch:gradle-download-task:3.4.3
     |    \--- org.apache.httpcomponents:httpclient:4.5.3 (*)
     +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.40
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.40
     |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.40 (*)
     |    \--- org.jetbrains.intellij.deps:trove4j:1.0.20181211
     +--- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.40
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.40 (*)
     +--- org.jetbrains.kotlin:kotlin-android-extensions:1.3.40
     |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.40 (*)
     +--- org.jetbrains.kotlin:kotlin-compiler-runner:1.3.40
     |    +--- org.jetbrains.kotlin:kotlin-build-common:1.3.40
     |    \--- org.jetbrains.kotlin:kotlin-daemon-client:1.3.40
     +--- org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.40
     |    +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.40
     |    |    +--- org.jetbrains.kotlin:kotlin-scripting-common:1.3.40
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     |    |    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1
     |    |    |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.40 (*)
     |    |    +--- org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.40
     |    |    |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.40
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     |    |    |    \--- org.jetbrains.kotlin:kotlin-scripting-common:1.3.40 (*)
     |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 (*)
     +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.40 (*)
     \--- org.jetbrains.kotlin:kotlin-reflect:1.3.40 (*)

发现原生的lint是走com.android.tools.external.com-intellij:kotlin-compiler:26.2.1 中的getEP_NAME()方法。没有问题。但是我的插件却走了org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.40中的 getEP_NAME()方法。我的kotlin版本必须是1.3.40，gradle版本必修是3.2.1，gradle版本决定了lint的版本必须是26.2.1。环境相同的情况下。android原生的lint没问题，我的增量插件却走了kotlin compiler库中的方法。导致执行的时候出上面的错误。请问当时你兼容的问题怎么解决的呢？

**Comment by tianwailaike61** [comment]
https://github.com/tianwailaike61/IncrementLint/blob/master/lib_lint_plugin/src/main/java/com/jianghongkui/lint/LintRunner.java

**Comment by tianwailaike61** [comment]
看下lintRunner里面的代码，建立classloader并利用反射改变了lint运行的环境，隔绝了项目中使用的kotlin对其影响。

**Comment by f2rozen541** [comment]
> 看下lintRunner里面的代码，建立classloader并利用反射改变了lint运行的环境，隔绝了项目中使用的kotlin对其影响。

你说的这种方式我试了。https://github.com/f2rozen541/test-lint 好像还是有问题。可以帮忙看下么？

**Comment by f2rozen541** [comment]
> 看下lintRunner里面的代码，建立classloader并利用反射改变了lint运行的环境，隔绝了项目中使用的kotlin对其影响。

clone下来直接运行./gradlew app:incrementLintDebug 就可以。

**Comment by Taylorswhisper** [comment]
> 看下lintRunner里面的代码，建立classloader并利用反射改变了lint运行的环境，隔绝了项目中使用的kotlin对其影响。

这种方式支持1.3.70以上版本吗？我这边使用1.3.70，自定义的增量插件还是报错了。该如何兼容呢
gradle-plugin版本3.4.3
lint版本26.4.3
kotlin-gradle-plugin1.3.70

**Comment by tianwailaike61** [comment]
报错信息贴一下

**Comment by Taylorswhisper** [comment]
1、跟楼主报的同样的错误，信息如下：
  Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.resolve.diagnostics.DiagnosticSuppressor$Companion.getEP_NAME()Lcom/intellij/openapi/extensions/ExtensionPointName;
        at com.android.tools.lint.LintCoreApplicationEnvironment.registerAppExtensionPoints(LintCoreApplicationEnvironment.java:170)
        at com.android.tools.lint.LintCoreApplicationEnvironment.createApplicationEnvironment(LintCoreApplicationEnvironment.java:103)
        at com.android.tools.lint.LintCoreApplicationEnvironment.get(LintCoreApplicationEnvironment.java:78)
        at com.android.tools.lint.LintCliClient.initializeProjects(LintCliClient.java:1240)
        at com.android.tools.lint.client.api.LintClient.performInitializeProjects$lint_api(LintClient.kt:846)
        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.kt:371)
        at com.android.tools.lint.LintCliClient.run(LintCliClient.java:237)
2、我按照网上查到的方法，尝试引入com.android.tools.external.com-intellij:kotlin-compiler:26.4.3，也还是报错，信息如下：
> Failed to notify project evaluation listener.
   > Could not create task ':app:compileDebugAndroidTestKotlin'.
      > KOTLIN_1_4
   > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.
3、“建立classloader并利用反射改变lint运行环境”的方法也有尝试过，我按照V3.6版本的方式进行适配，还是报错，错误信息与上面两种情况一样

**Comment by tianwailaike61** [comment]
> 1、跟楼主报的同样的错误，信息如下： Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.resolve.diagnostics.DiagnosticSuppressor$Companion.getEP_NAME()Lcom/intellij/openapi/extensions/ExtensionPointName; at com.android.tools.lint.LintCoreApplicationEnvironment.registerAppExtensionPoints(LintCoreApplicationEnvironment.java:170) at com.android.tools.lint.LintCoreApplicationEnvironment.createApplicationEnvironment(LintCoreApplicationEnvironment.java:103) at com.android.tools.lint.LintCoreApplicationEnvironment.get(LintCoreApplicationEnvironment.java:78) at com.android.tools.lint.LintCliClient.initializeProjects(LintCliClient.java:1240) at com.android.tools.lint.client.api.LintClient.performInitializeProjects$lint_api(LintClient.kt:846) at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.kt:371) at com.android.tools.lint.LintCliClient.run(LintCliClient.java:237) 2、我按照网上查到的方法，尝试引入com.android.tools.external.com-intellij:kotlin-compiler:26.4.3，也还是报错，信息如下：
> 
> > Failed to notify project evaluation listener.
> > Could not create task ':app:compileDebugAndroidTestKotlin'.
> > > KOTLIN_1_4
> > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.
> > 3、“建立classloader并利用反射改变lint运行环境”的方法也有尝试过，我按照V3.6版本的方式进行适配，还是报错，错误信息与上面两种情况一样

我使用和你相同的配置，lint正常执行了 
你可以看看AbsLintRunner这个类里面classPaths数据，使用的kotlin版本和gradle-plugin里面的版本是否一致
