### ISSUE TITLE
多个不同gradle版本项目应用

### ISSUE THREAD

**Issue by RudyJun** [tianwailaike61/IncrementLint#7]
如果lint-gradle版本需与gradle版本一一对应，那如果我将这个插件做成一个库，那其他不同项目因为gradle版本不一致是否无法使用
错误信息：
Bad invokespecial instruction: current class isn't assignable to reference class.
Exception Details:
  Location:
    com/jianghongkui/lint/IncrementLintTask.super$4$getVariantName()Ljava/lang/String; @1: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab7 01ab b0

**Comment by tianwailaike61** [comment]
可以写多个module，分别适配各个gradle版本，最后统一导入到lint_plugin里面，并根据不同的gradle版本判断调用不同module的内容，这样基本就能完成多gradle版本项目适配。

**Comment by RudyJun** [comment]
thx
